package com.drivevault.dashcam.domain.model

import com.drivevault.dashcam.data.local.entity.ClipEntity

data class Clip(
    val id: Long,
    val fileUri: String,
    val thumbnailUri: String?,
    val secondaryFileUri: String?,
    val secondaryThumbnailUri: String?,
    val startTimeMillis: Long,
    val endTimeMillis: Long,
    val durationMillis: Long,
    val cameraMode: CameraMode,
    val width: Int,
    val height: Int,
    val fps: Int,
    val bitrate: Int,
    val audioEnabled: Boolean,
    val overlayEnabled: Boolean,
    val miniMapEnabled: Boolean,
    val locked: Boolean,
    val startLatitude: Double,
    val startLongitude: Double,
    val endLatitude: Double,
    val endLongitude: Double,
    val averageSpeedMps: Double,
    val maxSpeedMps: Double,
    val startHeadingDegrees: Float,
    val endHeadingDegrees: Float,
    val immichStatus: ImmichStatus,
    val immichAssetId: String?,
    val immichSecondaryAssetId: String?,
    val fileSizeBytes: Long,
    val interrupted: Boolean,
    val createdAt: Long,
    val updatedAt: Long
)

fun ClipEntity.toDomain() = Clip(
    id = id,
    fileUri = fileUri,
    thumbnailUri = thumbnailUri,
    secondaryFileUri = secondaryFileUri,
    secondaryThumbnailUri = secondaryThumbnailUri,
    startTimeMillis = startTimeMillis,
    endTimeMillis = endTimeMillis,
    durationMillis = durationMillis,
    cameraMode = try { CameraMode.valueOf(cameraMode) } catch (_: Exception) { CameraMode.BACK },
    width = width,
    height = height,
    fps = fps,
    bitrate = bitrate,
    audioEnabled = audioEnabled,
    overlayEnabled = overlayEnabled,
    miniMapEnabled = miniMapEnabled,
    locked = locked,
    startLatitude = startLatitude,
    startLongitude = startLongitude,
    endLatitude = endLatitude,
    endLongitude = endLongitude,
    averageSpeedMps = averageSpeedMps,
    maxSpeedMps = maxSpeedMps,
    startHeadingDegrees = startHeadingDegrees,
    endHeadingDegrees = endHeadingDegrees,
    immichStatus = try { ImmichStatus.valueOf(immichStatus) } catch (_: Exception) { ImmichStatus.NOT_CONFIGURED },
    immichAssetId = immichAssetId,
    immichSecondaryAssetId = immichSecondaryAssetId,
    fileSizeBytes = fileSizeBytes,
    interrupted = interrupted,
    createdAt = createdAt,
    updatedAt = updatedAt
)

fun Clip.toEntity() = ClipEntity(
    id = id,
    fileUri = fileUri,
    thumbnailUri = thumbnailUri,
    secondaryFileUri = secondaryFileUri,
    secondaryThumbnailUri = secondaryThumbnailUri,
    startTimeMillis = startTimeMillis,
    endTimeMillis = endTimeMillis,
    durationMillis = durationMillis,
    cameraMode = cameraMode.name,
    width = width,
    height = height,
    fps = fps,
    bitrate = bitrate,
    audioEnabled = audioEnabled,
    overlayEnabled = overlayEnabled,
    miniMapEnabled = miniMapEnabled,
    locked = locked,
    startLatitude = startLatitude,
    startLongitude = startLongitude,
    endLatitude = endLatitude,
    endLongitude = endLongitude,
    averageSpeedMps = averageSpeedMps,
    maxSpeedMps = maxSpeedMps,
    startHeadingDegrees = startHeadingDegrees,
    endHeadingDegrees = endHeadingDegrees,
    immichStatus = immichStatus.name,
    immichAssetId = immichAssetId,
    immichSecondaryAssetId = immichSecondaryAssetId,
    fileSizeBytes = fileSizeBytes,
    interrupted = interrupted,
    createdAt = createdAt,
    updatedAt = updatedAt
)
